### ISSUE TITLE
Many many many persistent variables cannot be read

### ISSUE THREAD

**Issue by elconfa** [fbarresi/TwinCatAdsTool#1]
Hello I have a project with more then 53000 persistent var. Starting the backup funcion using the button READ FROM PLC, the program do non read all variable

**Comment by fbarresi** [comment]
Hi, 
Thank you for reporting your issue.

Wow, with 53000 variables you really have a big program. I guess even a json file would be extreme big.

Well, i review the implementation and, even if we tried the software with about 100/200 variables (including arrays and complex object), I think that in your case the Twincat driver will limit the requests in order to preserve the communication. I also guess, that reading 53000 times probably freeze your machine. (By the way I remember that one of the first ADS version was limited to 80 parallel readings)

I'm sorry, but I think i would not be able to find a solution to your problem, but may be we can add a new function where you can save or export filtered variables (it may be even better, than a single file with all that stuff).

What do you think about it?
Could that helps you?

**Comment by elconfa** [comment]
Wow, I think that is really good. Thanks a lot
Massimo

Il sab 18 gen 2020, 22:07 Federico Barresi <notifications@github.com> ha
scritto:

**Comment by elconfa** [comment]
I can send you an example of CSV file of persistent variable for my project

Il giorno dom 19 gen 2020 alle ore 09:23 Massimo Confalonieri <
massimoconfalonieri@gmail.com> ha scritto:

**Comment by fbarresi** [comment]
Could that be a bug related to #3 ?
Can you please check again with the latest software version?
Thank you.

**Comment by elconfa** [comment]
Yesterday I tested the new version on a project using 4500 persistent var and now it works well.
Today I tested the new version on a project using 51500 persistent var and now it works perfectly.
Thanks a lot.

Only one thing I would like to ask you:
does it is possible to save also the description of the variable?
Maybe in a future release, you can think about this new feature.

THANKS
Massimo
