### ISSUE TITLE
Add description of variables

### ISSUE THREAD

**Issue by elconfa** [fbarresi/TwinCatAdsTool#4]
Do you think it is possible to add this feature? In .json file, after every variable, add the description of the same variable?

Thanks.
Your application is very very useful!

Massimo

**Comment by fbarresi** [comment]
Hi,
I guess you mean such a comment for every variable, right?
Well, json doesn't actually support comments (see [stackoverflow](https://stackoverflow.com/questions/244777/can-comments-be-used-in-json))

Otherwise Json.Net supports them while parsing files. Writing them down would be possible, but also quite tricky...

I really don't know if we should try to implement this feature.
If you need a comment beside your variable, you probably didn't take care of naming rule.
Do you agree?

Can you tell any pros for this feature?

Cons:
- json file doesn't have the standard format
- json file is bigger
- not uniform if some comments is missing

**Comment by elconfa** [comment]
I'm sorry, I didn't know that Json file doesn't support comments.
Forget my request.

Tanks
Massimo
