### ISSUE TITLE
Support for multidimensional arrays

### ISSUE THREAD

**Issue by massimo-pizzardi** [fbarresi/TwinCatAdsTool#5]
I would like to send you my project with all persistent vars. I can read vars from PLC and save the file to PC.
I change the value (for example: Pers_CC._Setting[2][1]._DimensioneCass from 0.0 to 580.0) using Notepad++ and then load this file to TwinCAT ADS Tool. Pushing the button WRITE, I receive an error and nothing are written to PLC.

Please are you able to find the problem and to fix this? Thanks very much.

Massimo

[Backup_2020-07-07-111226.zip](https://github.com/fbarresi/TwinCatAdsTool/files/4883843/Backup_2020-07-07-111226.zip)

[TestFB.zip](https://github.com/fbarresi/TwinCatAdsTool/files/4883819/TestFB.zip)

**Comment by fbarresi** [comment]
Hi Massimo, 

are you using the latest software version?
I will give a try with your setup and let you know about it.

Best regards,
FB

**Comment by massimo-pizzardi** [comment]
Sorry, I forget to mention: I'm using the latest software version.
Thanks
Massimo

**Comment by fbarresi** [comment]
Hi Massimo, 

I gave a look to your project.

The problem you have regards this structure you defined with a multi dimensional array.

```restructured-text
TYPE DUT_Cass :
 STRUCT
  //...	
  _Setting : ARRAY [0..LastNastroConCassetti] OF ARRAY [0..MaxCassettiPerNastro] OF DUT_SettaggiCassetto;
  //...
 END_STRUCT
END_TYPE
```
I'm not sure if json format really supports multidimensional arrays, but json.net generates something like that:

```javascript
{
"GVL_PERSISTENT": {
    "Pers_CC": {
      "_Setting": [
        {
          "_Setting": [
            {...},
            {...}
              ]
            },
         {...}
      ]
}
```
The software than transforms json paths while writing to the plc like this: `GVL_PERSISTENT.Pers_CC._Settings[0]._Settings[0]` an that's of course wrong and in the right way should be `GVL_PERSISTENT.Pers_CC._Settings[0][0]` .

I will proof and refactor the logic for restoring variables from files, but I cannot promise the software will support multidimensional array so quickly also since I actually don't know if they are available in json.

For a quick workaroud I would adwise you to refactor your datatypes.

Best regards,

FB

**Comment by massimo-pizzardi** [comment]
"he software than transforms json paths while writing to the plc like this: GVL_PERSISTENT.Pers_CC._Settings[0]._Settings[0] an that's of course wrong and in the right way should be GVL_PERSISTENT.Pers_CC._Settings[0][0]"

That's not correct: the real variable is : GVL_PERSISTENT.Pers_CC._Settings[0][0]._Enable

Of course I use a lot of multi dimensional arrays.
Thanks for your work
Massimo

**Comment by fbarresi** [comment]
Hi Massimo, 

yes, I didn't mind a specific variable, but anyway... 
Json supports multidimensional arrays and json.net as well.
I have to fix the probem it in TwinCAT.JsonExtension.

Best regards, 
FB

**Comment by fbarresi** [comment]
Hi Massimo, 

I think I'm going to fix the problem in the next release.

Since I had to fix this problem in the json structure, some old backups made with the old software version cannot be restored automatically :disappointed_relieved: , but the files can be updated 😄 .

Feel free to reopen this issue if you find some other bugs.

Best regards,
FB
